language: cpp

sudo: required
os: linux
dist: trusty
compiler: gcc

notifications:
  email: false

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - ./install_prereqs.sh

script:
  - true

